from tasks.x11_task_error_group import run_process_data


def run():
    run_process_data()
