from tasks.x09_task_error_handling import get_data


def run():
    get_data.apply_async()
