from tasks.x12_task_error_chain import run_task_chain


def run():
    run_task_chain()
